name: "Setup cloud credentials"
description: "Setup cloud credentials"
inputs:
  aws_assume_role:
    description: 'AWS: AWS IAM Role for which to fetch credentials.'
  step:
    description: 'ALL: CI step that assumes permissions, must be 1 or 2 words split by "_". Or color of infra [GREEN, RED]. Used to name role session.'
  client_id:
    description: 'for azure'
  tenant_id:
    description: 'for azure'
  subscription_id:
    description: 'for azure'



runs:
  using: "composite"
  steps: 
    - name: Set globals
      id: globals
      shell: bash
      run: |
        echo "cloud=$(echo "${{ github.repository }}" | cut -d'-' -f 2)" >> "${GITHUB_OUTPUT}"
    
    - name: Authenticate with AWS Cloud
      # if: github.repository == 'epam/ecc-aws-rulepack'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_assume_role }}
        role-session-name: ECC-RULEPACK-CI-${{ inputs.step }}-${{ steps.globals.outputs.cloud }}
        role-duration-seconds: 43200 
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        mask-aws-account-id: true

    - name: Authenticate with Azure
      # if: github.repository == 'epam/ecc-azure-rulepack'
      uses: azure/login@v1
      with:
          client-id: ${{ inputs.client_id }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}
      
    - name: Run Azure CLI commands
      run: |
          az account show
    
    - uses: hashicorp/setup-terraform@v3
