name: "Publish logs to S3"
description: "Publish logs to S3"
inputs:
  local_path:
    required: true
  remote_path:
    required: true

runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        cloud=$(echo "${{ github.repository }}" | cut -d'-' -f 2)
        aws s3 cp ${{ inputs.local_path }} s3://${TF_BACKEND_STORAGE_NAME}/$cloud/${{ inputs.remote_path }} --recursive
