# This is a basic workflow to help you get started with Actions
name: Auto-testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'feature/auto_policy_testing'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      resource_priority_list:
        type: string
        description: Priority list for resources (you can remove unnecessary resources during testing)
        default: '["storage"]'
        required: true

# limits to only one workflow in time 
concurrency:
  group: ${{ github.workflow }}

env:
  AUTO_TEST_DIR: "auto_policy_testing"
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_SECRET_VALUE: ${{ secrets.AZURE_SECRET_VALUE }}
  default_resource_priority_list: '["storage"]'


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_common_resources:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compliance: ['green', 'red']
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/set-up-cloud-creds
  


    


















  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
