# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-azure-161-asb_appconfig_private_link
    description: |
      App Configuration service without Private Endpoint connection configured
    resource: azure.app-configuration
    filters:
      - type: value
        key: properties.privateEndpointConnections
        value: absent
    comment: '0240020000'
