# Copyright (c) 2025 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-azure-464-cis_app_insights_configured
    comment: '020032013800'
    description: |
      Subscription where Application Insights is not configured
    resource: azure.subscription
    filters:
      - type: missing
        policy:
          resource: azure.app-insights
          filters:
            - type: value
              key: properties.AppId
              value: present
            - type: value
              key: location
              value: present
            - type: value
              key: name
              value: present
            - type: value
              key: properties.provisioningState
              value: Succeeded
            - type: value
              key: properties.TenantId
              value: present
