name: "Install python dependencies"
description: "Install python dependencies"

runs:
  using: "composite"
  steps: 
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install dependencies
      shell: bash
      working-directory: auto_policy_testing/scripts
      run: |
        sudo apt-get install -y oathtool jq
        pip install --upgrade pip
        python3.10 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        