name: "Install python dependencies"
description: "Install python dependencies"

runs:
  using: "composite"
  steps: 
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install dependencies
      shell: bash
      working-directory: auto_policy_testing/scripts
      run: |
        sudo apt-get install -y oathtool jq
        pip install --upgrade pip
        python3.10 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        
        git clone https://$PROJECT_TOKEN@git.epam.com/epmc-eoos/cloudcustodian-sre-core.git --depth 1 --branch 'non-compatible-policies/all'
        cd cloudcustodian-sre-core
        pip install poetry
        make install
        
        # pip install c7n
        # pip install c7n-azure
        # pip install c7n-gcp
        

        cd ../../..
        cp -r  non-compatible-policies/. policies
