name: "Custodian scan"
description: "Custodian scan"

runs:
  using: "composite"
  steps: 
    - name: Custodian scan
      shell: bash
      working-directory: ${{ env.AUTO_TEST_DIR }}/scripts
      run: |
        export OUTPUT_DIR="${{ github.workspace }}/${AUTO_TEST_DIR}/output"
        echo "Running scan..."
        export cloud=$(echo "${{ github.repository }}" | cut -d'-' -f 2)

        source .venv/bin/activate
        python main.py \
        --cloud $cloud \
        --infra_color $COMPLINCE \
        --base_dir ${{ github.workspace }} \
        --output_dir $OUTPUT_DIR \
        --resource $RESOURCE \
        --auto_test_dir "${{ github.workspace }}/${AUTO_TEST_DIR}"
        
        echo "Failed policies:"
        cat ${OUTPUT_DIR}/.failed
        test -s ${OUTPUT_DIR}/.failed && exit 1
        exit 0